In [234]:
import torch

In [239]:
a = torch.tensor([1., 2., 3.])

In [240]:
def get_jacobian(net, x, noutputs):
    x.requires_grad 
    x = x.squeeze()
    n = x.size()[0]
    x = x.repeat(noutputs, 1)
    x.requires_grad_(True)
    y = net(x)
    y.backward(torch.eye(noutputs))
    return x.grad.data

In [241]:
get_jacobian(lambda x : 3 * x, a, 3)

tensor([[3., 0., 0.],
        [0., 3., 0.],
        [0., 0., 3.]])

In [231]:
x = torch.tensor([1., 2., 3., 4.], requires_grad=True)
x = x.repeat(2, 1)
print(x.shape)
x = x.detach()
x.requires_grad_(True)
weights = torch.randn(4, 2)
print(weights.shape)
y = x @ weights
print(y.shape)
y.backward(torch.tensor([[1., 0.], [0, 1.]]))
x.grad.data

torch.Size([2, 4])
torch.Size([4, 2])
torch.Size([2, 2])


tensor([[-1.4158,  1.9040, -0.3558, -0.5630],
        [-0.7212,  1.1231, -1.0444,  0.3104]])

In [232]:
import time

In [228]:
start = time.time()
x = torch.tensor([0.0, 2.0, 8.0], requires_grad = True)
y = torch.tensor([5.0 , 1.0 , 7.0], requires_grad = True)
z = x * y
print(z.shape)
z.backward(torch.tensor([1.0, 1.0, 1.0]))
print(x.grad)

torch.Size([3])
tensor([5., 1., 7.])


In [229]:
start = time.time()
x = torch.tensor([0.0, 2.0, 8.0], requires_grad = True)
y = torch.tensor([5.0 , 1.0 , 7.0], requires_grad = True)
z = torch.sum(x * y)
z.backward()
x.grad

tensor([5., 1., 7.])

## x = torch.tensor([[1., 2., 3.]]*3, requires_grad=True)
print(x)
y = 3 * x
y.backward(torch.eye(3))
x.grad.data

In [180]:
y.backward??

[[1.0, 2.0, 3.0],
 [1.0, 2.0, 3.0],
 [1.0, 2.0, 3.0],
 [1.0, 2.0, 3.0],
 [1.0, 2.0, 3.0],
 [1.0, 2.0, 3.0],
 [1.0, 2.0, 3.0],
 [1.0, 2.0, 3.0],
 [1.0, 2.0, 3.0],
 [1.0, 2.0, 3.0]]

In [133]:
net = lambda x : 3 * x
get_jacobian(net, a, noutputs=3)

tensor([1., 2., 3.], grad_fn=<SqueezeBackward0>)
3
tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]], grad_fn=<RepeatBackward>)
tensor([[3., 6., 9.],
        [3., 6., 9.],
        [3., 6., 9.]], grad_fn=<MulBackward0>)


AttributeError: 'NoneType' object has no attribute 'data'

In [95]:
def get_jacobian(net, x, noutputs):
    x = x.squeeze()
    n = x.size()[0]
    x = x.repeat(noutputs, 1)
    x.requires_grad_(True)
    y = net(x)
    y.backward(torch.eye(noutputs))
    return x.grad.data

In [100]:
def net(x):
    return 3 * x
get_jacobian(net, a, 3)

tensor([1., 2., 3.], grad_fn=<SqueezeBackward0>)
3
tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]], grad_fn=<RepeatBackward>)
tensor([[3., 6., 9.],
        [3., 6., 9.],
        [3., 6., 9.]], grad_fn=<MulBackward0>)


AttributeError: 'NoneType' object has no attribute 'data'